import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layouts/MainLayout";
import { ChatProvider } from "@/providers/ChatProvider";
import ChatUI from "@/features/chat/ChatUI";
import TextExplainerUI from "@/features/chat/TextExplainerUI";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ChatProvider>
          <MainLayout>{children}</MainLayout>
          <ChatUI />
          <TextExplainerUI />
        </ChatProvider>
      </body>
    </html>
  );
}
